default: &default
  adapter: postgresql
  encoding: unicode
  username: whiskeygrader

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: whiskey_grader_development
  password: password1

test:
  <<: *default
  database: whiskey_grader_test
  password: password1

production:
  <<: *default
  database: whiskey_grader_production
  username: whiskey_grader
  password: <%= ENV['WHISKEY_GRADER_DATABASE_PASSWORD'] %>
